name: run_test
on: [push]
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "CC=gcc-14.2" >> $GITHUB_ENV
      - run: echo "CXX=g++-14.2" >> $GITHUB_ENV
      - run: ./setup.sh
        working-directory: .
      - run: python3 run.py check
        working-directory: .
